config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get '/', to: 'shows#index'
    resources :categories
    resources :shows
    resources :bands
  end

  resources :shows, only: [ :index, :show ]

  root 'shows#index'

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/band.rb
class Admin::Band < ActiveRecord::Base
  belongs_to :admin_categories, :class_name => 'Admin::Category', foreign_key: :category_id
  has_many :admin_show, :class_name => 'Admin::Show'
end

app/models/admin/category.rb
class Admin::Category < ActiveRecord::Base
  has_many :admin_band, :class_name => 'Admin::Band'
end

app/models/admin/show.rb
class Admin::Show < ActiveRecord::Base
  belongs_to :admin_bands, :class_name => 'Admin::Band', foreign_key: :band_id
end

app/controllers/admin/bands_controller.rb
class Admin::BandsController < AdminController
  before_action :set_admin_band, only: [:show, :edit, :update, :destroy]

  # GET /admin/bands
  # GET /admin/bands.json
  def index
    @admin_bands = Admin::Band.all
  end

  # GET /admin/bands/1
  # GET /admin/bands/1.json
  def show
  end

  # GET /admin/bands/new
  def new
    @admin_band = Admin::Band.new
  end

  # GET /admin/bands/1/edit
  def edit
  end

  # POST /admin/bands
  # POST /admin/bands.json
  def create
    @admin_band = Admin::Band.new(admin_band_params)

    respond_to do |format|
      if @admin_band.save
        format.html { redirect_to @admin_band, notice: 'Band was successfully created.' }
        format.json { render :show, status: :created, location: @admin_band }
      else
        format.html { render :new }
        format.json { render json: @admin_band.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/bands/1
  # PATCH/PUT /admin/bands/1.json
  def update
    respond_to do |format|
      if @admin_band.update(admin_band_params)
        format.html { redirect_to @admin_band, notice: 'Band was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_band }
      else
        format.html { render :edit }
        format.json { render json: @admin_band.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/bands/1
  # DELETE /admin/bands/1.json
  def destroy
    @admin_band.destroy
    respond_to do |format|
      format.html { redirect_to admin_bands_url, notice: 'Band was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_band
      @admin_band = Admin::Band.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_band_params
      params.require(:admin_band).permit(:name, :category_id)
    end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  before_action :set_admin_category, only: [:show, :edit, :update, :destroy]

  # GET /admin/categories
  # GET /admin/categories.json
  def index
    @admin_categories = Admin::Category.all
  end

  # GET /admin/categories/1
  # GET /admin/categories/1.json
  def show
  end

  # GET /admin/categories/new
  def new
    @admin_category = Admin::Category.new
  end

  # GET /admin/categories/1/edit
  def edit
  end

  # POST /admin/categories
  # POST /admin/categories.json
  def create
    @admin_category = Admin::Category.new(admin_category_params)

    respond_to do |format|
      if @admin_category.save
        format.html { redirect_to @admin_category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @admin_category }
      else
        format.html { render :new }
        format.json { render json: @admin_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/categories/1
  # PATCH/PUT /admin/categories/1.json
  def update
    respond_to do |format|
      if @admin_category.update(admin_category_params)
        format.html { redirect_to @admin_category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_category }
      else
        format.html { render :edit }
        format.json { render json: @admin_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/categories/1
  # DELETE /admin/categories/1.json
  def destroy
    @admin_category.destroy
    respond_to do |format|
      format.html { redirect_to admin_categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_category
      @admin_category = Admin::Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_category_params
      params.require(:admin_category).permit(:name)
    end
end

app/controllers/admin/shows_controller.rb
class Admin::ShowsController < AdminController
  before_action :set_admin_show, only: [:show, :edit, :update, :destroy]

  # GET /admin/shows
  # GET /admin/shows.json
  def index
    @admin_shows = Admin::Show.all
  end

  # GET /admin/shows/1
  # GET /admin/shows/1.json
  def show
  end

  # GET /admin/shows/new
  def new
    @admin_show = Admin::Show.new
  end

  # GET /admin/shows/1/edit
  def edit
  end

  # POST /admin/shows
  # POST /admin/shows.json
  def create
    @admin_show = Admin::Show.new(admin_show_params)

    respond_to do |format|
      if @admin_show.save
        format.html { redirect_to @admin_show, notice: 'Show was successfully created.' }
        format.json { render :show, status: :created, location: @admin_show }
      else
        format.html { render :new }
        format.json { render json: @admin_show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/shows/1
  # PATCH/PUT /admin/shows/1.json
  def update
    respond_to do |format|
      if @admin_show.update(admin_show_params)
        format.html { redirect_to @admin_show, notice: 'Show was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_show }
      else
        format.html { render :edit }
        format.json { render json: @admin_show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/shows/1
  # DELETE /admin/shows/1.json
  def destroy
    @admin_show.destroy
    respond_to do |format|
      format.html { redirect_to admin_shows_url, notice: 'Show was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_show
      @admin_show = Admin::Show.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_show_params
      params.require(:admin_show).permit(:local, :date, :time, :description, :band_id)
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :set_admin_band, only: [ :show ]

  def index
    @shows = Admin::Show.all
  end

  def show
  end

  private

    def set_admin_band
      @show = Admin::Show.find(params[:id])
    end

end

app/helpers/admin/bands_helper.rb
module Admin::BandsHelper
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/shows_helper.rb
module Admin::ShowsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/admin/bands/_form.html.haml
= form_for @admin_band, html: { class: 'form' } do |f|
  -if @admin_band.errors.any?
    #error_explanation
      - @admin_band.errors.full_messages.each do |message|
        %li= message

  .field
    = f.text_field :name, placeholder: 'Nome', required: true
  .field
    = f.collection_select :category_id, Admin::Category.all, :id, :name, required: true

  .actions
    = f.submit 'Enviar'

app/views/admin/bands/edit.html.haml
#card
  %h1.title-f Editar banda

  = render 'form'

app/views/admin/bands/index.html.haml
#card
  %p#notice= notice

  %h1.title-f Bandas

  %table.table-list
    %thead
      %tr
        %th Nome
        %th Categoria
        %th.actions Ações
    %tbody
      - @admin_bands.each do |admin_band|
        %tr
          %td= admin_band.name
          %td= admin_band.admin_categories.name
          %td.actions
            = link_to 'Mostrar', admin_band
            = link_to 'Editar', edit_admin_band_path(admin_band)
            = link_to 'Excluir', admin_band, method: :delete, data: { confirm: 'Você tem certeza?' }

app/views/admin/bands/new.html.haml
#card
  %h1.title-f Nova banda

  = render 'form'

app/views/admin/bands/show.html.haml
#card
  %h1.title-f
    Banda #
    = @admin_band.id

  #notice= notice

  .show
    %p
      %strong Nome:
      = @admin_band.name

    %p
      %strong Category:
      = @admin_band.admin_categories.name

    = link_to 'Editar', edit_admin_band_path(@admin_band)
    = link_to 'Voltar', admin_bands_path

app/views/admin/categories/_form.html.haml
= form_for @admin_category, html: { class: 'form' } do |f|
  -if @admin_category.errors.any?
    #error_explanation
      - @admin_category.errors.full_messages.each do |message|
        %li= message

  .field
    = f.text_field :name, placeholder: 'Nome', required: true

  .actions
    = f.submit 'Enviar'

app/views/admin/categories/edit.html.haml
#card
  %h1.title-f Editar categoria

  = render 'form'

app/views/admin/categories/index.html.haml
#card
  %p#notice= notice

  %h1.title-f Categorias

  %table.table-list
    %thead
      %tr
        %th Nome
        %th.actions Ações
    %tbody
      - @admin_categories.each do |admin_category|
        %tr
          %td= admin_category.name
          %td.actions
            = link_to 'Mostrar', admin_category
            = link_to 'Editar', edit_admin_category_path(admin_category)
            = link_to 'Excluir', admin_category, method: :delete, data: { confirm: 'Você tem certeza?' }

app/views/admin/categories/new.html.haml
#card
  %h1.title-f Nova categoria

  = render 'form'

app/views/admin/categories/show.html.haml
#card
  %h1.title-f
    Banda #
    = @admin_category.id

  #notice= notice

  .show
    %p
      %strong Nome:
      = @admin_category.name

    = link_to 'Editar', edit_admin_category_path(@admin_category)
    = link_to 'Voltar', admin_categories_path

app/views/admin/shows/_form.html.haml
= form_for @admin_show, html: { class: 'form' } do |f|
  - if @admin_show.errors.any?
    #error_explanation
      %ul
        - @admin_show.errors.full_messages.each do |message|
          %li= message

  .field
    = f.text_field :local, placeholder: 'Local', required: true
  .field
    = f.date_select :date, {:use_month_names => ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro','Dezembro']}
  .field
    = f.text_field :time, placeholder: 'Horas', alt: 'time', required: true
  .field
    = f.text_area :description, placeholder: 'Descrição'
  .field
    = f.collection_select :band_id, Admin::Band.all, :id, :name, required: true
  .actions
    = f.submit 'Enviar'

:javascript
  $(document).ready(function() {
    $('input[type="text"]').setMask();
  });

app/views/admin/shows/edit.html.haml
#card
  %h1.title-f Editar show

  = render 'form'

app/views/admin/shows/index.html.haml
#card
  %p#notice= notice

  %h1.title-f Shows

  %table.table-list
    %thead
      %tr
        %th Local
        %th Data
        %th Banda
        %th.actions Ações
    %tbody
      - @admin_shows.each do |admin_show|
        %tr
          %td= admin_show.local
          %td= admin_show.date
          %td= admin_show.admin_bands.name
          %td.actions
            = link_to 'Mostrar', admin_show
            = link_to 'Editar', edit_admin_show_path(admin_show)
            = link_to 'Excluir', admin_show, method: :delete, data: { confirm: 'Você tem certeza?' }

app/views/admin/shows/new.html.haml
#card
  %h1.title-f Novo show

  = render 'form'

app/views/admin/shows/show.html.haml
#card
  %h1.title-f
    Banda #
    = @admin_show.id

  #notice= notice

  .show
    %p
      %strong Local:
      = @admin_show.local
    %p
      %strong Data:
      = @admin_show.date
    %p
      %strong Horas:
      = @admin_show.time
    %p
      %strong Descrição:
      = @admin_show.description
    %p
      %strong Banda:
      = @admin_show.admin_bands.name

    = link_to 'Editar', edit_admin_show_path(@admin_show)
    = link_to 'Voltar', admin_shows_path

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Painel administrativo</title>
  <%= stylesheet_link_tag    'admin' %>
  <%= javascript_include_tag 'admin' %>

  <link href='http://fonts.googleapis.com/css?family=Oswald:400,700,300' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Roboto:400,300italic,300,100italic,400italic,500' rel='stylesheet' type='text/css'>

  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/admin/top' %>

<main>

  <%= render 'layouts/admin/side' %>

  <section id="content">
    <%= yield %>
  </section>

</main>

</body>
</html>

app/views/layouts/admin/_side.html.haml
:javascript
  $(document).ready(function() {
    $('.menu .title').click(function(e) {
      $(this).next().slideToggle('slow');
      $(this).parent().toggleClass('open');
      e.preventDefault();
    });
  });

%aside#sidebar
  %ul.menu
    %li
      .title.category
        Categorias
        .box
      %ul.sub
        %li= link_to('Nova categoria', new_admin_category_path)
        %li= link_to('Listar categorias', admin_categories_path)
    %li
      .title.band
        Bandas
        .box
      %ul.sub
        %li= link_to('Nova banda', new_admin_band_path)
        %li= link_to('Listar bandas', admin_bands_path)
    %li
      .title.show
        Shows
        .box
      %ul.sub
        %li= link_to('Novo show', new_admin_show_path)
        %li= link_to('Listar shows', admin_shows_path)

app/views/layouts/admin/_top.html.haml
%header#header
  %h2 Painel Administrativo

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Agendamento</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Bitter:400,400italic,700' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/application/top' %>

<main>

  <%= yield %>

</main>

<%= render 'layouts/application/footer' %>


</body>
</html>

app/views/layouts/application/_footer.html.haml
%footer#footer
  %p Desenvolvido por Lucas Eduardo

app/views/layouts/application/_top.html.haml
%header#header
  .container
    %h2
      %span Agendamento
      de Shows

app/views/shows/index.html.haml
%main
  %section.list.container
    %h2.title-f Próximos shows

    - @shows.each do |show|
      %article
        .date
          = show.date
          = show.time
        .content
          %span.local= show.local
          = link_to show.admin_bands.name, show_path(show), class: :title
          %p= show.description
          = link_to 'Ver mais', show_path(show), class: :see
        .clearfix

app/views/shows/show.html.haml
%main
  %section.list.container
    %h2.title-f= @show.admin_bands.name

    %article
      .date
        = @show.date
        = @show.time
      .content
        %span.local= @show.local
        %p= @show.description
      .clearfix